
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


const evenFibNumbers = () => {
	const fibArr = [1];
	for (i = 2; fibArr[fibArr.length-1] < 4000000; i= fibArr[fibArr.length-1] + fibArr[fibArr.length-2]) {
		fibArr.push(i);
	}
	fibArr.pop();
	const fibSum = fibArr.reduce((acc, num) => {
		return num % 2 === 0 ? acc + num : acc;
	}, 0);
  console.log(fibSum);
}

evenFibNumbers();
